# Generated by Django 3.1.7 on 2021-04-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0004_auto_20210403_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Boast', 'Boast'), ('Roast', 'Roast')], default='Boast', max_length=10),
        ),
    ]
